### ISSUE TITLE
Improvements and recomendations

### ISSUE THREAD

**Issue by JMPMX** [jrassa/EmulationStation#101]
If I may, I would like to suggest some improvements to your wonderful frontend:

1) Implement another APIs to scrapping metada like: www.mobygames.com,  https://thegamesdb.net/ or https://screenscraper.fr/ (personally, actually the best)., because sometimes the base scrapper dont get all metadata or get incomplete.

2) Zip support for emulators that dont natively support it and are better than retroarch libretto. (Example: Snes9x or Kega Fusion) and then Goodmerge 7-Zip support to choose rom inside like others frontends (EmulatorsOrganizer, Emucenter2...) or emulator BizHawk, because old consoles or computers collections are romerged (Example: GoodSnes or GoodGen) with all versions of the game (Usa-Europe-Japan) plus Hack versions and (this is the most important) translated versions, and is important to choose what file you want to send to emulator to run. (attached video https://streamable.com/kaaxt)

Best regarts,

JMPM.

**Comment by jrassa** [comment]
This repo/project mirrors the RetroPie repository and will continue to do so.  Any changes will be made there first.

1. The built in scraper already supports gamesdb (default) and screenscraper.  There should be an option in the menu to switch.
2. The [RetroPie repo](https://github.com/RetroPie/EmulationStation) is always open to contributions if someone else would like to put together a PR.  However, I have no plans to add this feature myself.
